apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        api: geoapi
    spec:
      containers:
      - name: geoapi
        image: sashaz/geoapi:v5
        env:
        - name:  'GEO_KEY'
          value:  AIzaSyDr3iN4ZiOdk_X3t8Wx1s_Y6rvqxQUnsWI
        - name:  'GEO_DIR_KEY'
          value:  AIzaSyDp7yLyid5qJOIgQo1d_gt11NBBGCJivFA
        ports:
        - containerPort: 8099
        args:
        - node
        - server.js