apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        api: geoapi
    spec:
      containers:
      - name: geoapi
        image: sashaz/geoapi:v4
        env:
        - name:  'GEO_KEY'
          value:  AIzaSyDZszKJ0a72ED1ragcd0s3Eks3QI2wc6-I
        ports:
        - containerPort: 8099
        args:
        - node
        - server.js