apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: geoweb
    spec:
      containers:
      - name: geoweb
        image: sashaz/geoweb:v2
        ports:
        - containerPort: 80